# Generated by Django 3.1.6 on 2021-02-22 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(choices=[('SG', 'Sugestion'), ('CT', 'Criticism'), ('DV', 'Diverse')], default='SG', max_length=2),
        ),
    ]
